### PR TITLE
email verification part 2 (+ a few unrelated bugfixes)

### PR DESCRIPTION
**Pull request by silentwings**

### CODE REVIEW

**Comment by silentwings** [comment]
@abma: i've now done everything we discussed

**Comment by silentwings** [comment]
related changes (+ massive fixing) of documentation for lobby protocol, https://github.com/spring/LobbyProtocol/pull/38

**Comment by silentwings** [comment]
I thought it could be kept as a potential basis for a future matchmaking system, but as far as I can see it has no current purpose.

**Comment by abma** [comment]
i try to apply at the development server at springrts.com.

**Pull request merged**
