### PR TITLE
Allow to query user info

### PR DESCRIPTION
**Pull request by TurBoss**

### CODE REVIEW

**Comment by abma** [comment]
i did not fully investigate, but this function is used for the authentication replays.springrts.com: with an unset password the auth will succeed i guess?

thats not how it should work?!

when password is empty/none the function always should return 1.

**Comment by TurBoss** [comment]
Ok, I need to open a new pullrequest?

**Comment by abma** [comment]
no. new commits to the XMLRPC branch will automaticly show up here...

**Comment by TurBoss** [comment]
I think it should be OK now.

**Comment by TurBoss** [comment]
hello:

I did the changes you mentioned

is everything ok?

**Comment by abma** [comment]
thanks!

**Pull request merged**
