### PR TITLE
Include lobby version in ADDUSER

### PR DESCRIPTION
**Pull request by MasterBel2**
Adds a compatability flag `l`and sends lobby version as the final argument of ADDUSER to lobbies which have this compflag. Tested to work with [this fork of SL](https://github.com/MasterBel2/springlobby) (Thanks to ThinkSome for the help)

### CODE REVIEW

**Comment by abma** [comment]
IMHO: bad coding style, should be:

```

if receiver.compat['l']...:
    return ...
if receiver.compat['a']...:
    return...
return ...


```

**Comment by MasterBel2** [comment]
Good point (oops) but compat flags `l` and `a` aren't necessarily mutually exclusive? Unless `l` assumes conformance with `a`?

I'm not terribly familiar with python, but would it work to have something like:

```
if receiver.compat['l'] & receiver.compat['a']:
    return ...
if receiver.compat['l']:
    return ...
if receiver.compat['a']:
    return...
return ...
```

**Comment by abma** [comment]
KISS:
l without a makes no sense.  remove the "if receiver.compat['l'] and receiver.compat['a']:" branch please

**Comment by silentwings** [comment]
I wonder if its really a good idea to make the lobby _version_ accessible to all, since it risks advertising explicitly that users (who don't update) are vulnerable to any past/future security issues of their lobby clients.

**Comment by abma** [comment]
> I wonder if its a good idea to have the lobby version of all users sent to all other users, since it risks advertising very explicitly that some user has a lobby with outdated/broken security.

security by obscurity is a very bad idea, too.

not sure if this more an issue with privacy.

**Comment by abma** [comment]
cpu info should be removed when doing this change, too

**Pull request closed without merging**
