### PR TITLE
Requiriments for Venvs

### PR DESCRIPTION
**Pull request by TurBoss**
requires Geoip headers too from the distro

### CODE REVIEW

**Comment by abma** [comment]
oh, nice. never heard about venvs before. thanks!

**Comment by TurBoss** [comment]
ops forgot about mysqlclient

**Comment by gajop** [comment]
What are vens? Virtual environments?

**Comment by TurBoss** [comment]
yes

**Comment by abma** [comment]
venv's! :)

didn't test it but it should work like this:

python3 -m venv /path/to/new/virtual/environment
cd /path/to/new/virtual/environment
source bin/activate
pip install -r /path/to/requirements.txt

https://docs.python.org/3/library/venv.html

**Comment by gajop** [comment]
Oh, I didn't know about it, neat (although it doesn't work with 2.7 which is still a thing!)
I guess it's not that much different from typing `virtualenv --python=python3.5` which is what I usually do. I assume the prerequisites (pip) are identical?

**Comment by TurBoss** [comment]
yes the same

**Pull request merged**
