### PR TITLE
Twisted ssl [DISCUSSION]

### PR DESCRIPTION
**Pull request by TurBoss**
this allows the server to also listen on a ssl port

did this because I didn't manage to use my https://github.com/TurBoss/asyncspring to work with tls :(

ya I know not the best idea but here it is for discussion

I took the liberty to change tabs to spaces only on the server.py file

Thanks

### CODE REVIEW

**Comment by TurBoss** [comment]
sadly seems pretty broken

**Comment by abma** [comment]
please revert the tab to space changes. when at all it should change ALL files at once.

**Comment by TurBoss** [comment]
okay sorry

:+1:

**Comment by abma** [comment]
you don't need to close the pull request for doing new changes.

wrt: "did this because I didn't manage to use my https://github.com/TurBoss/asyncspring to work with tls :("

whats the problem?

**Comment by abma** [comment]
example client: https://github.com/spring/uberserver/blob/master/tests/tlsclient.py

**Pull request closed without merging**
